### ISSUE TITLE
Biosynth

### ISSUE THREAD

**Issue by schicks** [schicks/generations-in-the-dark#4]

**Comment by kraefrei** [comment]
So I had starting thinking about this, and I wonder if there are two factions, something in the vein of _The Academy_ folks who at one point were clinicians and esteemed biologists and have since started to dabble too far into 'Frankenstein' territory, and a separate group of essentially radicals who are at odds with them, because bio modification is for the people, for everybody. In the spirit of consolidating groups I could also see the scrappers being that group, although I do like the idea of there being conflict from both a group who wishes to maintain an ivory tower, and a group who is just interested in making a living moving whatever reclaimed stuff they can.

**Comment by schicks** [comment]
I love that idea! I have a few mentions already of **BioSynth** and definitely had been thinking about that as more the academy group. We should probably change that name to be something more formal, and have biosynth just refer to the thing both groups are _doing_. 

The other formal groups so far have pretty stodgy municipal names (Ship Defense Corp, Intership Council); I did some bouncing around with gemini for good acronyms and got CADMUS as a reference to the dragon teeth soldier story. The suggestions for what it stood for were mediocre, but my favorite was "Collective for the Advancement of Directed Morphogenetic Synthesis". Not wedded to it, but could be entertaining.

The radical group feels like it should have a less formal name, but I'm struggling more with what that should be.

**Comment by kraefrei** [comment]
Ultimately I was trialing out "Coven" as a name for that group and sticking with CADMUS for now. Felt like "coven" might be a fun analogy to play with at some level since they are vaguely cult territory. Could also see if we want to extend the Greek theming, but I like that they at some level stick out. See https://github.com/schicks/generations-in-the-dark/pull/26
